### ISSUE TITLE
IE Support Integration

### ISSUE THREAD

**Issue by ghost** [derrybarry/nagios-check_mk-dashing#1]
Hi @derrybarry ,

Since this repo is significantly different from that of <a href="https://github.com/Shopify/dashing">Shopify/dashing</a>, what would it take to integrate the Internet Explorer fixes found <a href="https://github.com/Shopify/dashing/pull/310">here</a> and <a href="https://github.com/Shopify/dashing/pull/322">here</a> into this project?

There are files and directories found in the <a href="https://github.com/Shopify/dashing/find/master">Dashing repo</a> that do not exist in this project:

Affected Files:
- <a href="https://github.com/Shopify/dashing/blob/master/dashing.gemspec">dashing.gemspec</a>
- <a href="https://github.com/Shopify/dashing/blob/master/javascripts/dashing.coffee">javascripts/dashing.coffee</a>
- <a href="https://github.com/Shopify/dashing/blob/master/lib/dashing/app.rb">lib/dashing/app.rb</a>

Directories:
- lib/dashing/*
- templates/project/*

Any help is appreciated, thank you.

Disclaimer: I do not use Internet Explorer, but there are some within my company that do. As such, it's my obligation to make sure they can view the dashboard using their browser of choice.

**Comment by derrybarry** [comment]
Have you tested the IE fixes in a base dashing install? I would do that before testing any further, from what i can see the changes mentions in #310 are to the main dashing framework, my repo is just a set of dashboards which are on a level above.

In short my advice for supporting IE would be build a base Dashing install, get that working with the changes from @liquidcc and then test if my repo works on that install first before going on to test on different browsers.

**Comment by derrybarry** [comment]
Closing Issue as it is related to the main dashing framework, not just this dashboard in particular
